
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author byron_rigdkvz
 */

public class Triangulo extends javax.swing.JFrame {

    /**
     * Creates new form Triangulo
     */
    public Triangulo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JLabel();
        jSubTitulo = new javax.swing.JLabel();
        TextLado1 = new javax.swing.JTextField();
        TextLado2 = new javax.swing.JTextField();
        TextLado3 = new javax.swing.JTextField();
        jValidar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        Jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitulo.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 102, 0));
        jTitulo.setText("TIPO DE TRIANGULOS");
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 320, 40));

        jSubTitulo.setBackground(new java.awt.Color(255, 255, 153));
        jSubTitulo.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jSubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jSubTitulo.setText("Favor ingrese la medida de los lados del trinagulo...");
        getContentPane().add(jSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));

        TextLado1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextLado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextLado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLado1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextLado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 80, 50));

        TextLado2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextLado2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TextLado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 80, 50));

        TextLado3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextLado3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextLado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLado3ActionPerformed(evt);
            }
        });
        getContentPane().add(TextLado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 80, 50));

        jValidar.setBackground(new java.awt.Color(204, 204, 204));
        jValidar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jValidar.setForeground(new java.awt.Color(51, 102, 255));
        jValidar.setText("VALIDAR");
        jValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValidarActionPerformed(evt);
            }
        });
        getContentPane().add(jValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, 50));

        jLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        jLimpiar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLimpiar.setForeground(new java.awt.Color(51, 102, 255));
        jLimpiar.setText("LIMPIAR");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 140, 50));

        jSalir.setBackground(new java.awt.Color(204, 204, 204));
        jSalir.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jSalir.setForeground(new java.awt.Color(51, 102, 255));
        jSalir.setText("SALIR");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, 50));

        Jfondo.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        Jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondonaranja2.jpg"))); // NOI18N
        getContentPane().add(Jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    
    private void jValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValidarActionPerformed
    int Lado1,Lado2,Lado3;
    Lado1=Integer.parseInt(TextLado1.getText());
    Lado2=Integer.parseInt(TextLado2.getText());
    Lado3=Integer.parseInt(TextLado3.getText());
    
    if (Lado1==Lado2 && Lado2==Lado3){
        JOptionPane.showMessageDialog(null,"El triángulo es Equilátero"); 
    }else if(Lado1==Lado2 && Lado2!=Lado3){
        JOptionPane.showMessageDialog(null,"El triángulo es Isósceles"); 
    }else if(Lado1==Lado3 && Lado2!=Lado3){
        JOptionPane.showMessageDialog(null,"El triángulo es Isósceles"); 
    }else if(Lado1!=Lado3 && Lado2==Lado3){
        JOptionPane.showMessageDialog(null,"El triángulo es Isósceles");    
    }else if(Lado1!=Lado3 && Lado2!=Lado3){
        JOptionPane.showMessageDialog(null,"El triángulo es Escaleno"); 
    }
    
    }//GEN-LAST:event_jValidarActionPerformed

    private void TextLado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLado3ActionPerformed

    private void TextLado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLado1ActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        TextLado1.setText("");
        TextLado2.setText("");
        TextLado3.setText("");
    }//GEN-LAST:event_jLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jfondo;
    private javax.swing.JTextField TextLado1;
    private javax.swing.JTextField TextLado2;
    private javax.swing.JTextField TextLado3;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JButton jSalir;
    private javax.swing.JLabel jSubTitulo;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JButton jValidar;
    // End of variables declaration//GEN-END:variables
}
